Repository team-grinder/alcohol-chat, pull requests merged in 2024-05, with the labels that each got.

#4 feat : entity setting
  src/main/java/com/alcoholchat/controller/entity/BoardController.java
  src/main/java/com/alcoholchat/controller/entity/ChatController.java
  src/main/java/com/alcoholchat/controller/entity/CommentController.java
  src/main/java/com/alcoholchat/controller/entity/ImageController.java
  src/main/java/com/alcoholchat/controller/entity/MemberController.java
  src/main/java/com/alcoholchat/controller/entity/PubController.java
  src/main/java/com/alcoholchat/controller/view/IndexController.java
  src/main/java/com/alcoholchat/domain/dto/BoardDTO.java
  src/main/java/com/alcoholchat/domain/dto/ChatDTO.java
  src/main/java/com/alcoholchat/domain/dto/CommentDTO.java
  src/main/java/com/alcoholchat/domain/dto/ImageDTO.java
  src/main/java/com/alcoholchat/domain/dto/MemberDTO.java
  src/main/java/com/alcoholchat/domain/dto/PubDTO.java
  src/main/java/com/alcoholchat/repository/BoardRepository.java
  src/main/java/com/alcoholchat/repository/ChatRepository.java
  src/main/java/com/alcoholchat/repository/CommentRepository.java
  src/main/java/com/alcoholchat/repository/ImageRepository.java
  src/main/java/com/alcoholchat/repository/MemberRepository.java
  src/main/java/com/alcoholchat/repository/PubRepository.java
  src/main/java/com/alcoholchat/service/BoardService.java
  src/main/java/com/alcoholchat/service/ChatService.java
  src/main/java/com/alcoholchat/service/CommentService.java
  src/main/java/com/alcoholchat/service/ImageService.java
  src/main/java/com/alcoholchat/service/MemberService.java
  src/main/java/com/alcoholchat/service/PubService.java
  src/main/java/com/alcoholchat/service/implement/BoardServiceImpl.java
  src/main/java/com/alcoholchat/service/implement/ChatServiceImpl.java
  src/main/java/com/alcoholchat/service/implement/CommentServiceImpl.java
  src/main/java/com/alcoholchat/service/implement/ImageServiceImpl.java
  src/main/java/com/alcoholchat/service/implement/MemberServiceImpl.java
  src/main/java/com/alcoholchat/service/implement/PubServiceImpl.java
Labels: enhancement

#7 feat : application-test.properties 추가
  build.gradle
  src/main/java/com/alcoholchat/domain/dto/BoardDTO.java
  src/main/java/com/alcoholchat/domain/dto/ChatDTO.java
  src/main/java/com/alcoholchat/domain/dto/CommentDTO.java
  src/main/java/com/alcoholchat/domain/dto/ImageDTO.java
  src/main/java/com/alcoholchat/domain/dto/MemberDTO.java
  src/main/java/com/alcoholchat/domain/dto/PubDTO.java
  src/main/resources/application-test.properties
  src/test/java/com/alcoholchat/AlcoholChatApplicationTests.java
Labels: enhancement

#15 Rename : 디렉토리 구조 설정 및 추가
  src/main/front/alcohol_chat/lib/core/core.dart
  src/main/front/alcohol_chat/lib/data/data.dart
  src/main/front/alcohol_chat/lib/data/data_source/local_storage/local_storage.dart
  src/main/front/alcohol_chat/lib/data/data_source/remote/remote.dart
  src/main/front/alcohol_chat/lib/data/dto/dto.dart
  src/main/front/alcohol_chat/lib/data/mapper/mapper.dart
  src/main/front/alcohol_chat/lib/data/repository_impl/repository_impl.dart
  src/main/front/alcohol_chat/lib/domain/entity/entity.dart
  src/main/front/alcohol_chat/lib/domain/repository/repository.dart
  src/main/front/alcohol_chat/lib/domain/usecase/usecase.dart
  src/main/front/alcohol_chat/lib/presentation/app.dart
  src/main/front/alcohol_chat/lib/presentation/pages/main/bloc/bloc.dart
  src/main/front/alcohol_chat/lib/presentation/pages/main/main_screen.dart
  src/main/front/alcohol_chat/lib/presentation/routes/routes.dart
Labels: documentation

#16 feat : QueryDSL 초기 셋팅
  build.gradle
  src/main/java/com/alcoholchat/repository/BoardRepository.java
  src/main/java/com/alcoholchat/repository/ChatRepository.java
  src/main/java/com/alcoholchat/repository/CommentRepository.java
  src/main/java/com/alcoholchat/repository/ImageRepository.java
  src/main/java/com/alcoholchat/repository/MemberRepository.java
  src/main/java/com/alcoholchat/repository/PubRepository.java
  src/main/java/com/alcoholchat/repository/queries/BoardQueryRepository.java
  src/main/java/com/alcoholchat/repository/queries/ChatQueryRepository.java
  src/main/java/com/alcoholchat/repository/queries/CommentQueryRepository.java
  src/main/java/com/alcoholchat/repository/queries/ImageQueryRepository.java
  src/main/java/com/alcoholchat/repository/queries/MemberQueryRepository.java
  src/main/java/com/alcoholchat/repository/queries/PubQueryRepository.java
  src/main/java/com/alcoholchat/repository/queries/implement/BoardQueryRepositoryImpl.java
  src/main/java/com/alcoholchat/repository/queries/implement/ChatQueryRepositoryImpl.java
  src/main/java/com/alcoholchat/repository/queries/implement/CommentQueryRepositoryImpl.java
  src/main/java/com/alcoholchat/repository/queries/implement/ImageQueryRepositoryImpl.java
  src/main/java/com/alcoholchat/repository/queries/implement/MemberQueryRepositoryImpl.java
  src/main/java/com/alcoholchat/repository/queries/implement/PubQueryRepositoryImpl.java
Labels: ✨enhancement

#19 feat pub api 구현
  src/main/java/com/alcoholchat/controller/entity/PubController.java
  src/main/java/com/alcoholchat/controller/responsehandler/PubApiResponseHandler.java
  src/main/java/com/alcoholchat/domain/dto/PubDTO.java
  src/main/java/com/alcoholchat/domain/dto/SuccessResult.java
  src/main/java/com/alcoholchat/domain/entity/Pub.java
  src/main/java/com/alcoholchat/repository/PubRepository.java
  src/main/java/com/alcoholchat/service/MemberService.java
  src/main/java/com/alcoholchat/service/PubService.java
  src/main/java/com/alcoholchat/service/implement/MemberServiceImpl.java
  src/main/java/com/alcoholchat/service/implement/PubServiceImpl.java
  src/main/resources/data.sql
Labels: ✨enhancement

#27 feat : pub test
  build.gradle
  src/test/java/com/alcoholchat/controller/entity/PubControllerTest.java
  src/test/java/com/alcoholchat/domain/entity/PubTest.java
  src/test/java/com/alcoholchat/repository/PubRepositoryTest.java
  src/test/java/com/alcoholchat/service/PubServiceTest.java
Labels: ✨enhancement, 💯test
